# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Giff < Formula
  desc "A terminal-based Git diff viewer with real-time updates"
  homepage "https://github.com/sukechannnn/giff"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sukechannnn/giff/releases/download/v0.2.3/giff_0.2.3_darwin_amd64.tar.gz"
      sha256 "e4a1a66e3aa977f238fc4ce6e656cedc9e1723c134f407ff50f8acf04d25c445"

      define_method(:install) do
        bin.install "giff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sukechannnn/giff/releases/download/v0.2.3/giff_0.2.3_darwin_arm64.tar.gz"
      sha256 "64bab082c7e66534e1f8d8b5f2fd30379ca19fa1324e0c68e0fb3bb82d48a491"

      define_method(:install) do
        bin.install "giff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukechannnn/giff/releases/download/v0.2.3/giff_0.2.3_linux_amd64.tar.gz"
      sha256 "37c38f5abc7a65407b5f58e7b35947186164769fe6b4729e3bc70ca1ffb6768b"
      define_method(:install) do
        bin.install "giff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sukechannnn/giff/releases/download/v0.2.3/giff_0.2.3_linux_arm64.tar.gz"
      sha256 "7ec18f7db62959438a4a513d836cc773403316be72daba7840b799a58eedc342"
      define_method(:install) do
        bin.install "giff"
      end
    end
  end

  test do
    system "#{bin}/giff", "-v"
  end
end
