# This file was generated by GoReleaser. DO NOT EDIT.
cask "giff" do
  version "0.2.7"

  on_macos do
    on_intel do
      sha256 "a5c197282ed865744e9951c5d3782e66e8f3d63d3084721a0a0bfc4dd0e891b7"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c73b567f3564000faefb40807bd1da41175fb386bc1b0921ee4dc17ddd6ab83"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "edb4a90607054a82aaeac8cba5369659907a087c4f61682c4b3c67b9bc6034c7"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b43c895c6fa0e11a17670f5858f57add9a06d08f33a5ee003c7b01298a961404"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "giff"
  desc "A terminal-based Git diff viewer with real-time updates"
  homepage "https://github.com/sukechannnn/giff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "giff"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/giff"]
    end
  end

  # No zap stanza required

end
