# This file was generated by GoReleaser. DO NOT EDIT.
cask "giff" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "14db635ef677a3acd1dcac8e0976101cc429f17141c30d0ec706df6782ccbdaf"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "078980e7a4d7b74971a20d02e2bc2398f0c4f7e0b480829bd5ee87c9950760a7"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c6d576e7c9e46aff9b6d0b71676fe08daae1b8bb119204e0a4059bd9c747a56d"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f020b749947535a09ee0bff9ba84299fde96049436a3657274d5ca5608ed9c8"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "giff"
  desc "A terminal-based Git diff viewer with real-time updates"
  homepage "https://github.com/sukechannnn/giff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "giff"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/giff"]
    end
  end

  # No zap stanza required
end
