# This file was generated by GoReleaser. DO NOT EDIT.
cask "giff" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "484697a8bfa60d5ee9fd07198ffdcb867a0132da5e456715e9dee6e438a62807"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "061be1be45cb21d4f5bc0755e601291bf83696b2734a3321743c38be98430402"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef43c08dbefe0dcceb72dc05f59675e2ed46a662ea58d320a0a0bf52b25f0c2a"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87253a278459aff1368a67045c4bc2f1431ccd3307a39adacc25cb81af5fa0ea"
      url "https://github.com/sukechannnn/giff/releases/download/v#{version}/giff_#{version}_linux_arm64.tar.gz"
    end
  end

  name "giff"
  desc "A terminal-based Git diff viewer with real-time updates"
  homepage "https://github.com/sukechannnn/giff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "giff"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/giff"]
    end
  end

  # No zap stanza required

end
